/*
 * Copyright (C) 2019~2023 dinstone<dinstone@163.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authir.proto

package com.dinstone.focus.protobuf;

public final class ArithProto {
    private ArithProto() {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor internal_static_message_ArithRequest_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_message_ArithRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor internal_static_message_ArithResponse_descriptor;
    static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internal_static_message_ArithResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        java.lang.String[] descriptorData = { "\n\014authir.proto\022\007message\"$\n\014ArithRequest\022"
                + "\t\n\001a\030\001 \001(\001\022\t\n\001b\030\002 \001(\001\"\032\n\rArithResponse\022\t"
                + "\n\001c\030\001 \001(\0012\346\001\n\014ArithService\0224\n\003Add\022\025.mess"
                + "age.ArithRequest\032\026.message.ArithResponse"
                + "\0224\n\003Sub\022\025.message.ArithRequest\032\026.message"
                + ".ArithResponse\0224\n\003Mul\022\025.message.ArithReq"
                + "uest\032\026.message.ArithResponse\0224\n\003Div\022\025.me"
                + "ssage.ArithRequest\032\026.message.ArithRespon" + "seB6\n\033com.dinstone.focus.protobufB\nArith"
                + "ProtoP\001Z\t/protocolb\006proto3" };
        descriptor = com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {});
        internal_static_message_ArithRequest_descriptor = getDescriptor().getMessageTypes().get(0);
        internal_static_message_ArithRequest_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_message_ArithRequest_descriptor, new java.lang.String[] { "A", "B", });
        internal_static_message_ArithResponse_descriptor = getDescriptor().getMessageTypes().get(1);
        internal_static_message_ArithResponse_fieldAccessorTable = new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_message_ArithResponse_descriptor, new java.lang.String[] { "C", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
